
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "dotphp/baseexception.zep.h"
#include "dotphp/base/dotbase.zep.h"
#include "dotphp/abstractbootstrap.zep.h"
#include "dotphp/interfaces/icontroller.zep.h"
#include "dotphp/base/processbase.zep.h"
#include "dotphp/bean/abstractresponsemessage.zep.h"
#include "dotphp/interfaces/idb.zep.h"
#include "dotphp/interfaces/iencoder.zep.h"
#include "dotphp/interfaces/ilogger.zep.h"
#include "dotphp/interfaces/iswooleeventdispatcher.zep.h"
#include "dotphp/argumentexception.zep.h"
#include "dotphp/base/multiprocessbase.zep.h"
#include "dotphp/base/swoolebase.zep.h"
#include "dotphp/base/webcontrollerbase.zep.h"
#include "dotphp/bean/cacheparameter.zep.h"
#include "dotphp/bean/dbparameter.zep.h"
#include "dotphp/bean/responsemessage.zep.h"
#include "dotphp/bean/routemessage.zep.h"
#include "dotphp/clibootstrap.zep.h"
#include "dotphp/configurationexception.zep.h"
#include "dotphp/core/genericlogger.zep.h"
#include "dotphp/core/socketclient.zep.h"
#include "dotphp/core/swooleeventdispatcher.zep.h"
#include "dotphp/dataexception.zep.h"
#include "dotphp/db/dbpdo.zep.h"
#include "dotphp/dbexception.zep.h"
#include "dotphp/dot.zep.h"
#include "dotphp/filenotfoundexception.zep.h"
#include "dotphp/httpexception.zep.h"
#include "dotphp/interfaces/iprocess.zep.h"
#include "dotphp/interfaces/irouteparser.zep.h"
#include "dotphp/interfaces/itemplate.zep.h"
#include "dotphp/notimplementedexception.zep.h"
#include "dotphp/parseexception.zep.h"
#include "dotphp/permissionexception.zep.h"
#include "dotphp/runtimeexception.zep.h"
#include "dotphp/socketexception.zep.h"
#include "dotphp/swoolebootstrap.zep.h"
#include "dotphp/utils/arrayutil.zep.h"
#include "dotphp/utils/encoder.zep.h"
#include "dotphp/utils/number.zep.h"
#include "dotphp/utils/path.zep.h"
#include "dotphp/utils/probability.zep.h"
#include "dotphp/utils/stringutil.zep.h"
#include "dotphp/validateexception.zep.h"
#include "dotphp/webbootstrap.zep.h"

#endif